version: '3.8'

volumes:
  postgres:
  pgadmin:

services:
  postgres:
    container_name: demo_postgres
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432'

  pgadmin:
    container_name: demo_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - '5050:5050'
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:myuser:secret' > /tmp/pgpassfile && chmod /tmp/pgpassfile && /entrypoint.sh"